version: '3'

services:
  urlshortener:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - "STORAGE_TYPE=inmem"
    ports:
      - "8000:8000"

