version: '3'

services:
  postgres:
    image: postgres:14
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - "./storage/db/:/docker-entrypoint-initdb.d/"
      - "./postgres-data:/var/lib/postgresql/data"

  urlshortener:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - "STORAGE_TYPE=db"
    ports:
      - "8000:8000"
    depends_on:
      - postgres

